import Head from 'next/head'

import { Inter } from '@next/font/google'
import { useRouter } from 'next/router'
import { NextPageWithLayout } from '@/models'
import { Box, Button, ButtonBase, NoSsr, styled, Typography } from '@mui/material'
import Image from 'mui-image'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPageWithLayout = () => {

  const router = useRouter()
 
  const ImageButton = styled(ButtonBase)(({ theme }) => ({
    position: 'relative',
    height: 200,
    [theme.breakpoints.down('sm')]: {
      width: '100% !important', // Overrides inline-style
      height: 100,
    },
    '&:hover, &.Mui-focusVisible': {
      zIndex: 1,
      '& .MuiImageBackdrop-root': {
        opacity: 0.15,
      },
      '& .MuiImageMarked-root': {
        opacity: 0,
      },
      '& .MuiTypography-root': {
        border: '4px solid currentColor',
      },
    },
  }));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NoSsr>
        <Box sx={{
          alignItems: 'center',
          display: 'flex',
          justifyContent: 'center',
          paddingTop: '4rem'
        }}
       >
          <Image src='/ss_icon.png' width={'15rem'} height={'15rem'}></Image>
        </Box>
      </NoSsr>

      <Typography variant='body1' sx={{
        textAlign: 'center',
        paddingTop: '4rem',
      }}>
        <b>Welcome to Swag Soft WEBAR demo.</b>

      </Typography>

      <Typography variant='body1' sx={{
        textAlign: 'center',
        paddingBottom: '10rem',
      }}>

        Please tap on the <b>camera</b> icon to commence experience

      </Typography>

      <NoSsr>
        <Box sx={{ justifyContent: 'center', alignItems: 'center', alignContent: 'center', display: 'flex',  }}>
          <Button variant='contained' color='inherit' startIcon={<Image src='/ic_camera.svg' width={'5rem'} bgColor='transparent' />}
            sx={{
              backgroundColor: 'transparent',
              background: '#ffffff',        
              p : 1,     
              "& .MuiButton-startIcon" : {margin : "0px"}
            }}
            onClick={() =>{
              router.push('/scanner')
            }}
            >
          </Button>
        </Box>
      </NoSsr>
    </div>
  )
}

// Home.Layout = MainLayout 

export default Home